runtime: custom
env: flex

service: default

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  SERVER_PORT: 8080
  BPL_JVM_THREAD_COUNT: 50
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=1g -XX:ReservedCodeCacheSize=120M -XX:MaxMetaspaceSize=80M"